parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $url: '%env(resolve:APP_URL)%'
            $path: '%env(resolve:APP_PATH)%'
            $phoneNumber: '%env(resolve:APP_PHONE_NUMBER)%'
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'